### ISSUE TITLE
Markup loading but assets are not (PHP).

### ISSUE THREAD

**Issue by ghost** [eric1234/rack-legacy#12]
Hi,

I have just about got this working on my machine but when I navigate to my site, I receive a 500 error in the console for all images, css files and javascript files. The markup has loaded though

Have I missed something?

**Comment by ghost** [comment]
The problem is coming from the "use Rack::Legacy::Cgi, Dir.getwd" line in the config.ru file:

If I remove that line and restart pow, my PHP pages render correctly. 

I have also changed the INDEXES line in the config.ru file but I doubt that has had any effect on this issue. The line now reads: "INDEXES = [index.php']".

**Comment by ghost** [comment]
Ok its a file permission issue, I had seen this on another thread but ignored it thinking that it wasn't applicable to this issue. Sorry for wasting your time.

Just so the information is here incase anyone needs it, from my project directory I ran the following commands in terminal:

find . -type d -print0 | xargs -0 chmod 744 # for directories
find . -type f -print0 | xargs -0 chmod 664 # for files

This changes all directories and sub directories to readwriteexecute read read & all files and files in sub directories to readwrite read read

**Comment by eric1234** [comment]
Yes, if your assets were marked executable then it would have tried to execute them as CGI files instead of simply serving them as static assets. BTW, I just made a new release that gets rid of the need for the rack-rewrite mess you are using. It also executes the PHP MUCH faster since PHP is left running between requests.

**Comment by ghost** [comment]
Ok, thanks for letting me know, I will update ASAP.
