### ISSUE TITLE
htm extension

### ISSUE THREAD

**Issue by ghost** [eric1234/rack-legacy#14]
Hi, this isn't really a serious issue but I was wondering how I could use index.htm as my default page. Using rack-rewrite, I just added index.htm to the INDEXES array but obviously when the rewrite script isn't present, no default page is found.

Should I just include the rewrite script or is there another way around this?

**Comment by eric1234** [comment]
rack-rewrite is not needed. I recently added [Rack::Legacy::Index](https://github.com/eric1234/rack-legacy/blob/master/lib/rack/legacy/index.rb) which removes the need for any sort of rack-rewrite hack.

You should notice Rack::Legacy::Index takes a list of "index" files to check for as it's second argument. Defaults to the standard ones (index.php, index.cgi, index.html). So assuming the following rackup file:

```
require 'rack/showexceptions'
require 'rack-legacy'

use Rack::ShowExceptions
use Rack::Legacy::Index
use Rack::Legacy::Php
use Rack::Legacy::Cgi
run Rack::File.new Dir.getwd
```

All we want to do is change it to:

```
require 'rack/showexceptions'
require 'rack-legacy'

use Rack::ShowExceptions
use Rack::Legacy::Index, Dir.getwd, ['index.php', 'index.cgi', 'index.html', 'index.htm']
use Rack::Legacy::Php
use Rack::Legacy::Cgi
run Rack::File.new Dir.getwd
```

Feel free to remove any index files you are not using.

**Comment by ghost** [comment]
Ahh brilliant, I wasn't aware of Index. Thankyou very much :o)
