### ISSUE TITLE
Wordpress factory?

### ISSUE THREAD

**Issue by fotanus** [eric1234/rack-legacy#16]
Hi I wonder if you can help me?

I'm trying to create a wordpress factory software, that is, a software that installs multiple wordpress softwares. Since is for internal use, I would like to avoid having to mess with apache files, and decided to try rack-legacy to host the PHP sites.

It seems to work fine with a configuration like this:

```
config.middleware.insert_before ActionDispatch::Static, Rack::Legacy::Php, Rails.public_path.to_s + "/wordpress/test"
```

But then, the wordpress "test" is accessed through the `/` (so, to access it I should type `/index.php` instead of `/wordpress/test/index.php`). This is not what I want, because this way I can't access more than one wordpress at once. 

So, my question: is there a way to define a "route" for the php files?

Thanks for the attention!

**Comment by eric1234** [comment]
Yes, you should be able to mount a Rack app as an endpoint in Rails. See [the Rails docs](http://guides.rubyonrails.org/routing.html#routing-to-rack-applications) for the syntax. I'm not exactly sure how arguments are given to the rack app but a little research should turn up an answer.

Closing this issue as it is more of a Rails configuration issue and not a problem with Rack Legacy. But it should be possible. Good luck.

**Comment by fotanus** [comment]
Hi eric,

Ok, thanks for your help!

Regards,
Felipe
