### ISSUE TITLE
PATH_INFO problem? 

### ISSUE THREAD

**Issue by marzocchi** [eric1234/rack-legacy#2]
Hi, 

I think there might be an issue with the value of PATH_INFO, which is different from what PHP
expects, at least when running as an Apache module. This difference breaks apps or frameworks relying
on it for clean URLs.

[Here is the relevant documentation](http://www.php.net/manual/en/reserved.variables.server.php).

For example a request for "/foo.php/bar" should result in
$_SERVER['PATH_INFO'] being set to "/bar", instead of "/foo.php/bar".

Now I'm not sure where this problem lies (rack, rack-legacy, or PHP itself) so I'm just submitting it for
your consideration. It might deserve a notice on the rack-legacy wiki page.

**Comment by eric1234** [comment]
That for reporting this. mherb noticed the same thing and submitted a patch which I just applied. Let me know if this fixes your problem or if you are still having a problem.
