### ISSUE TITLE
Where do the PHP logs go

### ISSUE THREAD

**Issue by wprater** [eric1234/rack-legacy#6]
php.ini states they should be heading to syslog, but I don't see them there and Im getting a 500 from rack-legacy.

```
Internal Server Error

An error was encountered while executing under the rack-legacy middleware.
```

**Comment by eric1234** [comment]
I am not adjusting how PHP logs data. Rack-legacy is just calling the PHP CGI binary to execute the code providing it the right inputs and capturing the output. Does the error message contain anything more than what you posted above? The error page is designed to output all the info that PHP gives it.

**Comment by wprater** [comment]
Good to know.  Unfortunately, nothing more is output besides the environment.

**Comment by eric1234** [comment]
If you run the PHP script from the command line does it run successfully?

**Comment by wprater** [comment]
Just the output headers.  

```
 (master *) % php-cgi index.php 
X-Powered-By: PHP/5.4.3
Content-type: text/html
```

Must be an issue with this PHP application.

**Comment by eric1234** [comment]
Yea, PHP can do that sometimes. It will encounter an error and die before it can output the why. I have never figured out when and why that happens exactly. Think it may be related to using the output buffer but unsure. Either way the best way to debug in this case is to:

```
echo 'Got here';
die;
```

Keep moving this bit later and later into the code until you don't get "Got here" anymore. Then move back until you get it again until you have narrowed down what is getting you the error. Primitive but it eventually works. :)

**Comment by wprater** [comment]
Yeah.. thats' what I've been trying.  Thanks for the help!
